import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Universités des pays d'études non couverts (story 5.11).
 *
 * `studyCountriesSeed` (src/scripts/data/country-availability.ts) déclare 12 pays
 * ouverts aux études, et la base confirme bien `studyAvailable = true` sur ces 12.
 * Or la table `universities` n'en couvrait que 4 — Germany (27), France (9),
 * Italy (6), United Kingdom (2) — plus Belgium (4) et Luxembourg (1) qui ne sont
 * pas dans la liste. Huit pays annoncés à l'étudiant n'avaient donc **aucune**
 * université : United States, Canada, Netherlands, Spain, Sweden, Switzerland,
 * Portugal, China.
 *
 * Format identique à `seed-universities.ts` : `{ name, city, country, website,
 * applicationUrl, specialty, programs: [{ name, level }] }`. Les intitulés de
 * filières suivent la convention majoritaire du catalogue — discipline en
 * français pour les Bachelors, préfixe « Master en » pour les Masters.
 *
 * ⚠️ `requiredLanguage` / `requiredLanguageLevel` : aucune des 49 universités
 * existantes ne les renseignait. Les valeurs posées ici sont la **langue
 * principale d'enseignement** et un **niveau plancher indicatif** cohérent avec les
 * exigences habituellement publiées (B2 ≈ IELTS 6.0-6.5, C1 ≈ IELTS 7.0+).
 * Elles ne remplacent pas la fiche officielle de chaque programme : une filière
 * anglophone dans un pays non anglophone, ou une sélection plus stricte, doit être
 * corrigée à la main depuis l'admin.
 */
const universitiesData = [
  // ─── UNITED STATES ────────────────────────────────────────────────────────
  {
    name: 'Massachusetts Institute of Technology (MIT)',
    city: 'Cambridge (Massachusetts)',
    country: 'United States',
    website: 'https://www.mit.edu',
    applicationUrl: 'https://mitadmissions.org/apply/',
    specialty: 'Référence mondiale en ingénierie, informatique et innovation',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'C1',
    programs: [
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Génie électrique', level: 'Bachelor' },
      { name: 'Génie mécanique', level: 'Bachelor' },
      { name: 'Physique', level: 'Bachelor' },
      { name: 'Mathématiques', level: 'Bachelor' },
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Master en Intelligence artificielle', level: 'Master' },
      { name: 'Master en Informatique', level: 'Master' },
      { name: 'Master en Ingénierie', level: 'Master' },
      { name: 'Master en Management technologique', level: 'Master' },
    ],
  },
  {
    name: 'Stanford University',
    city: 'Stanford (Californie)',
    country: 'United States',
    website: 'https://www.stanford.edu',
    applicationUrl: 'https://admission.stanford.edu/apply/',
    specialty: 'Excellence en informatique, entrepreneuriat et sciences du vivant',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'C1',
    programs: [
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Génie civil', level: 'Bachelor' },
      { name: 'Biologie', level: 'Bachelor' },
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Psychologie', level: 'Bachelor' },
      { name: 'Master en Data Science', level: 'Master' },
      { name: 'Master en Entrepreneuriat', level: 'Master' },
      { name: 'Master en Management', level: 'Master' },
      { name: 'Master en Sciences biomédicales', level: 'Master' },
    ],
  },
  {
    name: 'Harvard University',
    city: 'Cambridge (Massachusetts)',
    country: 'United States',
    website: 'https://www.harvard.edu',
    applicationUrl: 'https://college.harvard.edu/admissions/apply',
    specialty: 'Prestige académique, droit, médecine et sciences politiques',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'C1',
    programs: [
      { name: 'Droit', level: 'Bachelor' },
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Sciences politiques', level: 'Bachelor' },
      { name: 'Histoire', level: 'Bachelor' },
      { name: 'Philosophie', level: 'Bachelor' },
      { name: 'Master en Droit international', level: 'Master' },
      { name: 'Master en Santé publique', level: 'Master' },
      { name: 'Master en Politique publique', level: 'Master' },
      { name: 'Master en Management', level: 'Master' },
    ],
  },
  {
    name: 'University of California, Berkeley',
    city: 'Berkeley (Californie)',
    country: 'United States',
    website: 'https://www.berkeley.edu',
    applicationUrl: 'https://admissions.berkeley.edu/apply/',
    specialty: 'Université publique de premier plan, sciences et ingénierie',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'C1',
    programs: [
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Génie électrique', level: 'Bachelor' },
      { name: 'Chimie', level: 'Bachelor' },
      { name: 'Biologie', level: 'Bachelor' },
      { name: 'Sciences de l’environnement', level: 'Bachelor' },
      { name: 'Sociologie', level: 'Bachelor' },
      { name: 'Master en Data Science', level: 'Master' },
      { name: 'Master en Développement durable', level: 'Master' },
      { name: 'Master en Ingénierie', level: 'Master' },
    ],
  },
  {
    name: 'Columbia University',
    city: 'New York',
    country: 'United States',
    website: 'https://www.columbia.edu',
    applicationUrl: 'https://undergrad.admissions.columbia.edu/apply',
    specialty: 'Journalisme, relations internationales et affaires publiques',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'C1',
    programs: [
      { name: 'Journalisme', level: 'Bachelor' },
      { name: 'Relations internationales', level: 'Bachelor' },
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Architecture', level: 'Bachelor' },
      { name: 'Master en Journalisme', level: 'Master' },
      { name: 'Master en Relations internationales', level: 'Master' },
      { name: 'Master en Finance', level: 'Master' },
      { name: 'Master en Santé publique', level: 'Master' },
    ],
  },
  {
    name: 'University of Michigan',
    city: 'Ann Arbor (Michigan)',
    country: 'United States',
    website: 'https://umich.edu',
    applicationUrl: 'https://admissions.umich.edu/apply',
    specialty: 'Grande université publique, ingénierie et sciences sociales',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Génie mécanique', level: 'Bachelor' },
      { name: 'Sciences infirmières', level: 'Bachelor' },
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Psychologie', level: 'Bachelor' },
      { name: 'Master en Ingénierie', level: 'Master' },
      { name: 'Master en Management', level: 'Master' },
      { name: 'Master en Santé publique', level: 'Master' },
    ],
  },

  // ─── CANADA ───────────────────────────────────────────────────────────────
  {
    name: 'University of Toronto',
    city: 'Toronto',
    country: 'Canada',
    website: 'https://www.utoronto.ca',
    applicationUrl: 'https://future.utoronto.ca/apply/',
    specialty: 'Première université canadienne, recherche pluridisciplinaire',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Génie civil', level: 'Bachelor' },
      { name: 'Commerce', level: 'Bachelor' },
      { name: 'Sciences politiques', level: 'Bachelor' },
      { name: 'Psychologie', level: 'Bachelor' },
      { name: 'Master en Intelligence artificielle', level: 'Master' },
      { name: 'Master en Santé publique', level: 'Master' },
      { name: 'Master en Management', level: 'Master' },
    ],
  },
  {
    name: 'McGill University',
    city: 'Montréal',
    country: 'Canada',
    website: 'https://www.mcgill.ca',
    applicationUrl: 'https://www.mcgill.ca/applying/',
    specialty: 'Université anglophone de Montréal, médecine et sciences',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Droit', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Génie électrique', level: 'Bachelor' },
      { name: 'Biologie', level: 'Bachelor' },
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Master en Neurosciences', level: 'Master' },
      { name: 'Master en Droit international', level: 'Master' },
      { name: 'Master en Management', level: 'Master' },
    ],
  },
  {
    name: 'University of British Columbia (UBC)',
    city: 'Vancouver',
    country: 'Canada',
    website: 'https://www.ubc.ca',
    applicationUrl: 'https://you.ubc.ca/applying-ubc/',
    specialty: 'Sciences de l’environnement, océanographie et durabilité',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Sciences de l’environnement', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Génie civil', level: 'Bachelor' },
      { name: 'Biologie', level: 'Bachelor' },
      { name: 'Commerce', level: 'Bachelor' },
      { name: 'Master en Développement durable', level: 'Master' },
      { name: 'Master en Sciences du climat', level: 'Master' },
      { name: 'Master en Informatique', level: 'Master' },
    ],
  },
  {
    name: 'Université de Montréal',
    city: 'Montréal',
    country: 'Canada',
    website: 'https://www.umontreal.ca',
    applicationUrl: 'https://admission.umontreal.ca/',
    specialty: 'Grande université francophone, santé et intelligence artificielle',
    requiredLanguage: 'Français',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Droit', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Psychologie', level: 'Bachelor' },
      { name: 'Sciences infirmières', level: 'Bachelor' },
      { name: 'Master en Intelligence artificielle', level: 'Master' },
      { name: 'Master en Santé publique', level: 'Master' },
      { name: 'Master en Linguistique', level: 'Master' },
    ],
  },
  {
    name: 'University of Waterloo',
    city: 'Waterloo (Ontario)',
    country: 'Canada',
    website: 'https://uwaterloo.ca',
    applicationUrl: 'https://uwaterloo.ca/future-students/admissions',
    specialty: 'Informatique et ingénierie, alternance en entreprise réputée',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Génie logiciel', level: 'Bachelor' },
      { name: 'Mathématiques', level: 'Bachelor' },
      { name: 'Génie mécanique', level: 'Bachelor' },
      { name: 'Master en Informatique', level: 'Master' },
      { name: 'Master en Cybersecurity', level: 'Master' },
      { name: 'Master en Data Science', level: 'Master' },
    ],
  },
  {
    name: 'Université Laval',
    city: 'Québec',
    country: 'Canada',
    website: 'https://www.ulaval.ca',
    applicationUrl: 'https://www.ulaval.ca/admission',
    specialty: 'Plus ancienne université francophone d’Amérique du Nord',
    requiredLanguage: 'Français',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Droit', level: 'Bachelor' },
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Agronomie', level: 'Bachelor' },
      { name: 'Sciences de l’environnement', level: 'Bachelor' },
      { name: 'Administration des affaires', level: 'Bachelor' },
      { name: 'Master en Développement durable', level: 'Master' },
      { name: 'Master en Management', level: 'Master' },
    ],
  },

  // ─── NETHERLANDS ──────────────────────────────────────────────────────────
  {
    name: 'Delft University of Technology (TU Delft)',
    city: 'Delft',
    country: 'Netherlands',
    website: 'https://www.tudelft.nl/en/',
    applicationUrl: 'https://www.tudelft.nl/en/education/admission-and-application',
    specialty: 'Première université technique néerlandaise, ingénierie et design',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Génie civil', level: 'Bachelor' },
      { name: 'Génie mécanique', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Architecture', level: 'Bachelor' },
      { name: 'Design industriel', level: 'Bachelor' },
      { name: 'Master en Ingénierie', level: 'Master' },
      { name: 'Master en Renewable Energy', level: 'Master' },
      { name: 'Master en Intelligence artificielle', level: 'Master' },
    ],
  },
  {
    name: 'University of Amsterdam',
    city: 'Amsterdam',
    country: 'Netherlands',
    website: 'https://www.uva.nl/en',
    applicationUrl: 'https://www.uva.nl/en/education/admissions',
    specialty: 'Sciences sociales, économie et communication',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Sciences politiques', level: 'Bachelor' },
      { name: 'Psychologie', level: 'Bachelor' },
      { name: 'Communication', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Master en Data Science', level: 'Master' },
      { name: 'Master en Communication', level: 'Master' },
      { name: 'Master en Migration Studies', level: 'Master' },
    ],
  },
  {
    name: 'Utrecht University',
    city: 'Utrecht',
    country: 'Netherlands',
    website: 'https://www.uu.nl/en',
    applicationUrl: 'https://www.uu.nl/en/education/admission-and-application',
    specialty: 'Sciences du vivant, durabilité et sciences humaines',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Biologie', level: 'Bachelor' },
      { name: 'Chimie', level: 'Bachelor' },
      { name: 'Sciences de l’environnement', level: 'Bachelor' },
      { name: 'Histoire', level: 'Bachelor' },
      { name: 'Droit', level: 'Bachelor' },
      { name: 'Master en Développement durable', level: 'Master' },
      { name: 'Master en Biologie quantitative', level: 'Master' },
    ],
  },
  {
    name: 'Leiden University',
    city: 'Leyde',
    country: 'Netherlands',
    website: 'https://www.universiteitleiden.nl/en',
    applicationUrl: 'https://www.universiteitleiden.nl/en/education/admissions',
    specialty: 'Droit international, sciences humaines et archéologie',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Droit', level: 'Bachelor' },
      { name: 'Relations internationales', level: 'Bachelor' },
      { name: 'Archéologie', level: 'Bachelor' },
      { name: 'Langues étrangères', level: 'Bachelor' },
      { name: 'Psychologie', level: 'Bachelor' },
      { name: 'Master en Droit international', level: 'Master' },
      { name: 'Master en Archéologie', level: 'Master' },
    ],
  },
  {
    name: 'Eindhoven University of Technology (TU/e)',
    city: 'Eindhoven',
    country: 'Netherlands',
    website: 'https://www.tue.nl/en/',
    applicationUrl: 'https://www.tue.nl/en/education/admission-and-enrolment',
    specialty: 'Ingénierie, électronique et systèmes intelligents',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Génie électrique', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Génie mécanique', level: 'Bachelor' },
      { name: 'Sciences des matériaux', level: 'Bachelor' },
      { name: 'Master en Ingénierie', level: 'Master' },
      { name: 'Master en Data Science', level: 'Master' },
    ],
  },
  {
    name: 'Erasmus University Rotterdam',
    city: 'Rotterdam',
    country: 'Netherlands',
    website: 'https://www.eur.nl/en',
    applicationUrl: 'https://www.eur.nl/en/education/admission-application',
    specialty: 'Économie, management et santé publique',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Administration des affaires', level: 'Bachelor' },
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Droit', level: 'Bachelor' },
      { name: 'Master en Finance', level: 'Master' },
      { name: 'Master en Management', level: 'Master' },
      { name: 'Master en Santé publique', level: 'Master' },
    ],
  },

  // ─── SPAIN ────────────────────────────────────────────────────────────────
  {
    name: 'Universidad Complutense de Madrid',
    city: 'Madrid',
    country: 'Spain',
    website: 'https://www.ucm.es',
    applicationUrl: 'https://www.ucm.es/estudios/acceso',
    specialty: 'Plus grande université d’Espagne, offre pluridisciplinaire',
    requiredLanguage: 'Espagnol',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Droit', level: 'Bachelor' },
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Journalisme', level: 'Bachelor' },
      { name: 'Psychologie', level: 'Bachelor' },
      { name: 'Histoire', level: 'Bachelor' },
      { name: 'Master en Droit international', level: 'Master' },
      { name: 'Master en Communication', level: 'Master' },
    ],
  },
  {
    name: 'Universitat de Barcelona',
    city: 'Barcelone',
    country: 'Spain',
    website: 'https://www.ub.edu',
    applicationUrl: 'https://www.ub.edu/portal/web/admissions',
    specialty: 'Recherche en sciences du vivant et sciences humaines',
    requiredLanguage: 'Espagnol',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Biologie', level: 'Bachelor' },
      { name: 'Chimie', level: 'Bachelor' },
      { name: 'Philosophie', level: 'Bachelor' },
      { name: 'Langues étrangères', level: 'Bachelor' },
      { name: 'Master en Neurosciences', level: 'Master' },
      { name: 'Master en Biotechnologies', level: 'Master' },
    ],
  },
  {
    name: 'Universidad Autónoma de Madrid',
    city: 'Madrid',
    country: 'Spain',
    website: 'https://www.uam.es',
    applicationUrl: 'https://www.uam.es/uam/estudios/acceso-admision',
    specialty: 'Sciences fondamentales et droit',
    requiredLanguage: 'Espagnol',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Physique', level: 'Bachelor' },
      { name: 'Mathématiques', level: 'Bachelor' },
      { name: 'Droit', level: 'Bachelor' },
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Master en Physique théorique', level: 'Master' },
      { name: 'Master en Mathématiques appliquées', level: 'Master' },
    ],
  },
  {
    name: 'Universitat Autònoma de Barcelona (UAB)',
    city: 'Barcelone',
    country: 'Spain',
    website: 'https://www.uab.cat/en/',
    applicationUrl: 'https://www.uab.cat/web/study/admission',
    specialty: 'Vétérinaire, communication et sciences de l’environnement',
    requiredLanguage: 'Espagnol',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Médecine vétérinaire', level: 'Bachelor' },
      { name: 'Communication', level: 'Bachelor' },
      { name: 'Sciences de l’environnement', level: 'Bachelor' },
      { name: 'Biologie', level: 'Bachelor' },
      { name: 'Sociologie', level: 'Bachelor' },
      { name: 'Master en Développement durable', level: 'Master' },
      { name: 'Master en Communication', level: 'Master' },
    ],
  },
  {
    name: 'Universitat Politècnica de València',
    city: 'Valence',
    country: 'Spain',
    website: 'https://www.upv.es/en',
    applicationUrl: 'https://www.upv.es/entidades/sa/admision',
    specialty: 'Université technique, ingénierie et design',
    requiredLanguage: 'Espagnol',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Génie civil', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Design industriel', level: 'Bachelor' },
      { name: 'Architecture', level: 'Bachelor' },
      { name: 'Agronomie', level: 'Bachelor' },
      { name: 'Master en Ingénierie', level: 'Master' },
      { name: 'Master en Renewable Energy', level: 'Master' },
    ],
  },
  {
    name: 'Universidad de Navarra',
    city: 'Pampelune',
    country: 'Spain',
    website: 'https://www.unav.edu/en/',
    applicationUrl: 'https://www.unav.edu/en/admission',
    specialty: 'Médecine, communication et management',
    requiredLanguage: 'Espagnol',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Sciences infirmières', level: 'Bachelor' },
      { name: 'Journalisme', level: 'Bachelor' },
      { name: 'Administration des affaires', level: 'Bachelor' },
      { name: 'Master en Management', level: 'Master' },
      { name: 'Master en Santé publique', level: 'Master' },
    ],
  },

  // ─── SWEDEN ───────────────────────────────────────────────────────────────
  {
    name: 'Karolinska Institutet',
    city: 'Stockholm',
    country: 'Sweden',
    website: 'https://ki.se/en',
    applicationUrl: 'https://ki.se/en/education/admissions',
    specialty: 'Institut médical de référence, jury du prix Nobel de médecine',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Sciences infirmières', level: 'Bachelor' },
      { name: 'Sciences biomédicales', level: 'Bachelor' },
      { name: 'Master en Santé publique', level: 'Master' },
      { name: 'Master en Neurosciences', level: 'Master' },
      { name: 'Master en Biotechnologies', level: 'Master' },
    ],
  },
  {
    name: 'Lund University',
    city: 'Lund',
    country: 'Sweden',
    website: 'https://www.lunduniversity.lu.se',
    applicationUrl: 'https://www.lunduniversity.lu.se/admissions',
    specialty: 'Université pluridisciplinaire, forte ouverture internationale',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Droit', level: 'Bachelor' },
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Génie électrique', level: 'Bachelor' },
      { name: 'Sciences de l’environnement', level: 'Bachelor' },
      { name: 'Master en Développement durable', level: 'Master' },
      { name: 'Master en Droit international', level: 'Master' },
      { name: 'Master en Innovation', level: 'Master' },
    ],
  },
  {
    name: 'KTH Royal Institute of Technology',
    city: 'Stockholm',
    country: 'Sweden',
    website: 'https://www.kth.se/en',
    applicationUrl: 'https://www.kth.se/en/studies/master/admissions',
    specialty: 'Première école d’ingénieurs suédoise',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Génie électrique', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Génie mécanique', level: 'Bachelor' },
      { name: 'Architecture', level: 'Bachelor' },
      { name: 'Master en Ingénierie', level: 'Master' },
      { name: 'Master en Renewable Energy', level: 'Master' },
      { name: 'Master en Data Science', level: 'Master' },
    ],
  },
  {
    name: 'Uppsala University',
    city: 'Uppsala',
    country: 'Sweden',
    website: 'https://www.uu.se/en',
    applicationUrl: 'https://www.uu.se/en/study/apply',
    specialty: 'Plus ancienne université de Scandinavie',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Physique', level: 'Bachelor' },
      { name: 'Droit', level: 'Bachelor' },
      { name: 'Histoire', level: 'Bachelor' },
      { name: 'Langues étrangères', level: 'Bachelor' },
      { name: 'Master en Physique', level: 'Master' },
      { name: 'Master en Développement durable', level: 'Master' },
    ],
  },
  {
    name: 'Stockholm University',
    city: 'Stockholm',
    country: 'Sweden',
    website: 'https://www.su.se/english/',
    applicationUrl: 'https://www.su.se/english/education/apply',
    specialty: 'Sciences sociales, droit et sciences naturelles',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Sciences politiques', level: 'Bachelor' },
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Psychologie', level: 'Bachelor' },
      { name: 'Chimie', level: 'Bachelor' },
      { name: 'Master en Sciences du climat', level: 'Master' },
      { name: 'Master en Relations internationales', level: 'Master' },
    ],
  },
  {
    name: 'Chalmers University of Technology',
    city: 'Göteborg',
    country: 'Sweden',
    website: 'https://www.chalmers.se/en/',
    applicationUrl: 'https://www.chalmers.se/en/education/apply/',
    specialty: 'Ingénierie, architecture navale et technologies durables',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Génie mécanique', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Architecture', level: 'Bachelor' },
      { name: 'Sciences des matériaux', level: 'Bachelor' },
      { name: 'Master en Ingénierie', level: 'Master' },
      { name: 'Master en Renewable Energy', level: 'Master' },
    ],
  },

  // ─── SWITZERLAND ──────────────────────────────────────────────────────────
  {
    name: 'ETH Zürich',
    city: 'Zurich',
    country: 'Switzerland',
    website: 'https://ethz.ch/en.html',
    applicationUrl: 'https://ethz.ch/en/studies/registration-application.html',
    specialty: 'Première université technique d’Europe continentale',
    requiredLanguage: 'Allemand',
    requiredLanguageLevel: 'C1',
    programs: [
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Génie mécanique', level: 'Bachelor' },
      { name: 'Physique', level: 'Bachelor' },
      { name: 'Mathématiques', level: 'Bachelor' },
      { name: 'Architecture', level: 'Bachelor' },
      { name: 'Master en Intelligence artificielle', level: 'Master' },
      { name: 'Master en Ingénierie', level: 'Master' },
      { name: 'Master en Sciences du climat', level: 'Master' },
    ],
  },
  {
    name: 'École polytechnique fédérale de Lausanne (EPFL)',
    city: 'Lausanne',
    country: 'Switzerland',
    website: 'https://www.epfl.ch/en/',
    applicationUrl: 'https://www.epfl.ch/education/admission/',
    specialty: 'Ingénierie, robotique et sciences du numérique',
    requiredLanguage: 'Français',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Génie électrique', level: 'Bachelor' },
      { name: 'Génie civil', level: 'Bachelor' },
      { name: 'Sciences des matériaux', level: 'Bachelor' },
      { name: 'Master en Robotique', level: 'Master' },
      { name: 'Master en Data Science', level: 'Master' },
      { name: 'Master en Renewable Energy', level: 'Master' },
    ],
  },
  {
    name: 'Université de Genève',
    city: 'Genève',
    country: 'Switzerland',
    website: 'https://www.unige.ch',
    applicationUrl: 'https://www.unige.ch/admissions/',
    specialty: 'Relations internationales, droit et sciences humaines',
    requiredLanguage: 'Français',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Relations internationales', level: 'Bachelor' },
      { name: 'Droit', level: 'Bachelor' },
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Psychologie', level: 'Bachelor' },
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Master en Droit international', level: 'Master' },
      { name: 'Master en Relations internationales', level: 'Master' },
    ],
  },
  {
    name: 'Universität Zürich',
    city: 'Zurich',
    country: 'Switzerland',
    website: 'https://www.uzh.ch/en.html',
    applicationUrl: 'https://www.uzh.ch/en/studies/application.html',
    specialty: 'Plus grande université suisse, médecine et sciences économiques',
    requiredLanguage: 'Allemand',
    requiredLanguageLevel: 'C1',
    programs: [
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Droit', level: 'Bachelor' },
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Master en Finance', level: 'Master' },
      { name: 'Master en Neurosciences', level: 'Master' },
    ],
  },
  {
    name: 'Universität Basel',
    city: 'Bâle',
    country: 'Switzerland',
    website: 'https://www.unibas.ch/en.html',
    applicationUrl: 'https://www.unibas.ch/en/Studies/Application.html',
    specialty: 'Sciences de la vie et pharmacie',
    requiredLanguage: 'Allemand',
    requiredLanguageLevel: 'C1',
    programs: [
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Sciences pharmaceutiques', level: 'Bachelor' },
      { name: 'Biologie', level: 'Bachelor' },
      { name: 'Histoire', level: 'Bachelor' },
      { name: 'Master en Biotechnologies', level: 'Master' },
      { name: 'Master en Sciences pharmaceutiques', level: 'Master' },
    ],
  },
  {
    name: 'Università della Svizzera italiana (USI)',
    city: 'Lugano',
    country: 'Switzerland',
    website: 'https://www.usi.ch/en',
    applicationUrl: 'https://www.usi.ch/en/education/admission',
    specialty: 'Communication, informatique et architecture, en italien et anglais',
    requiredLanguage: 'Italien',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Communication', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Architecture', level: 'Bachelor' },
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Master en Communication', level: 'Master' },
      { name: 'Master en Informatique', level: 'Master' },
    ],
  },

  // ─── PORTUGAL ─────────────────────────────────────────────────────────────
  {
    name: 'Universidade de Lisboa',
    city: 'Lisbonne',
    country: 'Portugal',
    website: 'https://www.ulisboa.pt/en',
    applicationUrl: 'https://www.ulisboa.pt/en/acesso-e-ingresso',
    specialty: 'Plus grande université portugaise, offre complète',
    requiredLanguage: 'Portugais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Droit', level: 'Bachelor' },
      { name: 'Génie civil', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Lettres', level: 'Bachelor' },
      { name: 'Master en Ingénierie', level: 'Master' },
      { name: 'Master en Droit international', level: 'Master' },
    ],
  },
  {
    name: 'Universidade do Porto',
    city: 'Porto',
    country: 'Portugal',
    website: 'https://www.up.pt/portal/en/',
    applicationUrl: 'https://www.up.pt/portal/en/study/admissions/',
    specialty: 'Ingénierie, médecine et beaux-arts',
    requiredLanguage: 'Portugais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Génie mécanique', level: 'Bachelor' },
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Architecture', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Arts', level: 'Bachelor' },
      { name: 'Master en Ingénierie', level: 'Master' },
      { name: 'Master en Design', level: 'Master' },
    ],
  },
  {
    name: 'Universidade de Coimbra',
    city: 'Coimbra',
    country: 'Portugal',
    website: 'https://www.uc.pt/en/',
    applicationUrl: 'https://www.uc.pt/en/candidatos/',
    specialty: 'Université historique classée au patrimoine mondial',
    requiredLanguage: 'Portugais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Droit', level: 'Bachelor' },
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Histoire', level: 'Bachelor' },
      { name: 'Physique', level: 'Bachelor' },
      { name: 'Master en Droit international', level: 'Master' },
      { name: 'Master en Histoire', level: 'Master' },
    ],
  },
  {
    name: 'Universidade NOVA de Lisboa',
    city: 'Lisbonne',
    country: 'Portugal',
    website: 'https://www.unl.pt/en',
    applicationUrl: 'https://www.unl.pt/en/study/admissions',
    specialty: 'Économie, santé publique et technologies',
    requiredLanguage: 'Portugais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Sciences de l’environnement', level: 'Bachelor' },
      { name: 'Sociologie', level: 'Bachelor' },
      { name: 'Master en Finance', level: 'Master' },
      { name: 'Master en Santé publique', level: 'Master' },
    ],
  },
  {
    name: 'Universidade do Minho',
    city: 'Braga',
    country: 'Portugal',
    website: 'https://www.uminho.pt/EN',
    applicationUrl: 'https://www.uminho.pt/EN/education/admissions',
    specialty: 'Ingénierie des matériaux et biotechnologies',
    requiredLanguage: 'Portugais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Sciences des matériaux', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Biologie', level: 'Bachelor' },
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Master en Biotechnologies', level: 'Master' },
      { name: 'Master en Ingénierie', level: 'Master' },
    ],
  },
  {
    name: 'Universidade de Aveiro',
    city: 'Aveiro',
    country: 'Portugal',
    website: 'https://www.ua.pt/en/',
    applicationUrl: 'https://www.ua.pt/en/candidaturas',
    specialty: 'Télécommunications, céramique et sciences de la mer',
    requiredLanguage: 'Portugais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Génie électrique', level: 'Bachelor' },
      { name: 'Sciences des matériaux', level: 'Bachelor' },
      { name: 'Biologie marine', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Master en Ingénierie', level: 'Master' },
      { name: 'Master en Développement durable', level: 'Master' },
    ],
  },

  // ─── CHINA ────────────────────────────────────────────────────────────────
  {
    name: 'Tsinghua University',
    city: 'Pékin',
    country: 'China',
    website: 'https://www.tsinghua.edu.cn/en/',
    applicationUrl: 'https://www.tsinghua.edu.cn/en/Admissions.htm',
    specialty: 'Première université chinoise en ingénierie et informatique',
    requiredLanguage: 'Chinois',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Génie électrique', level: 'Bachelor' },
      { name: 'Génie civil', level: 'Bachelor' },
      { name: 'Architecture', level: 'Bachelor' },
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Master en Intelligence artificielle', level: 'Master' },
      { name: 'Master en Ingénierie', level: 'Master' },
      { name: 'Master en Management', level: 'Master' },
    ],
  },
  {
    name: 'Peking University',
    city: 'Pékin',
    country: 'China',
    website: 'https://english.pku.edu.cn',
    applicationUrl: 'https://english.pku.edu.cn/admissions/',
    specialty: 'Sciences humaines, droit et sciences fondamentales',
    requiredLanguage: 'Chinois',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Droit', level: 'Bachelor' },
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Philosophie', level: 'Bachelor' },
      { name: 'Physique', level: 'Bachelor' },
      { name: 'Langues étrangères', level: 'Bachelor' },
      { name: 'Master en Relations internationales', level: 'Master' },
      { name: 'Master en Économie', level: 'Master' },
    ],
  },
  {
    name: 'Fudan University',
    city: 'Shanghai',
    country: 'China',
    website: 'https://www.fudan.edu.cn/en/',
    applicationUrl: 'https://iso.fudan.edu.cn/admissions.htm',
    specialty: 'Médecine, journalisme et sciences économiques',
    requiredLanguage: 'Chinois',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Journalisme', level: 'Bachelor' },
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Master en Santé publique', level: 'Master' },
      { name: 'Master en Journalisme', level: 'Master' },
    ],
  },
  {
    name: 'Shanghai Jiao Tong University',
    city: 'Shanghai',
    country: 'China',
    website: 'https://en.sjtu.edu.cn',
    applicationUrl: 'https://isc.sjtu.edu.cn/EN/',
    specialty: 'Ingénierie navale, mécanique et sciences des données',
    requiredLanguage: 'Chinois',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Génie mécanique', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Génie électrique', level: 'Bachelor' },
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Master en Data Science', level: 'Master' },
      { name: 'Master en Ingénierie', level: 'Master' },
    ],
  },
  {
    name: 'Zhejiang University',
    city: 'Hangzhou',
    country: 'China',
    website: 'https://www.zju.edu.cn/english/',
    applicationUrl: 'https://www.zju.edu.cn/english/admissions.htm',
    specialty: 'Agronomie, informatique et innovation industrielle',
    requiredLanguage: 'Chinois',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Agronomie', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Génie mécanique', level: 'Bachelor' },
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Master en Intelligence artificielle', level: 'Master' },
      { name: 'Master en Innovation', level: 'Master' },
    ],
  },
  {
    name: 'University of Science and Technology of China (USTC)',
    city: 'Hefei',
    country: 'China',
    website: 'https://en.ustc.edu.cn',
    applicationUrl: 'https://ic.ustc.edu.cn/en/',
    specialty: 'Physique quantique, mathématiques et sciences fondamentales',
    requiredLanguage: 'Chinois',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Physique', level: 'Bachelor' },
      { name: 'Mathématiques', level: 'Bachelor' },
      { name: 'Chimie', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Master en Physique théorique', level: 'Master' },
      { name: 'Master en Nanosciences', level: 'Master' },
    ],
  },

  // ─── UNITED KINGDOM (renfort : la base n'avait qu'Oxford et Cambridge) ─────
  {
    name: 'Imperial College London',
    city: 'Londres',
    country: 'United Kingdom',
    website: 'https://www.imperial.ac.uk',
    applicationUrl: 'https://www.imperial.ac.uk/study/apply/',
    specialty: 'Sciences, ingénierie, médecine et management',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'C1',
    programs: [
      { name: 'Génie mécanique', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Physique', level: 'Bachelor' },
      { name: 'Mathématiques', level: 'Bachelor' },
      { name: 'Master en Intelligence artificielle', level: 'Master' },
      { name: 'Master en Ingénierie', level: 'Master' },
      { name: 'Master en Santé publique', level: 'Master' },
    ],
  },
  {
    name: 'University College London (UCL)',
    city: 'Londres',
    country: 'United Kingdom',
    website: 'https://www.ucl.ac.uk',
    applicationUrl: 'https://www.ucl.ac.uk/prospective-students/undergraduate/apply',
    specialty: 'Université pluridisciplinaire, architecture et neurosciences',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'C1',
    programs: [
      { name: 'Architecture', level: 'Bachelor' },
      { name: 'Médecine', level: 'Bachelor' },
      { name: 'Droit', level: 'Bachelor' },
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Master en Neurosciences', level: 'Master' },
      { name: 'Master en Développement durable', level: 'Master' },
    ],
  },
  {
    name: 'London School of Economics and Political Science (LSE)',
    city: 'Londres',
    country: 'United Kingdom',
    website: 'https://www.lse.ac.uk',
    applicationUrl: 'https://www.lse.ac.uk/study-at-lse/undergraduate/how-to-apply',
    specialty: 'Économie, sciences politiques et sciences sociales',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'C1',
    programs: [
      { name: 'Économie', level: 'Bachelor' },
      { name: 'Sciences politiques', level: 'Bachelor' },
      { name: 'Droit', level: 'Bachelor' },
      { name: 'Sociologie', level: 'Bachelor' },
      { name: 'Relations internationales', level: 'Bachelor' },
      { name: 'Master en Finance', level: 'Master' },
      { name: 'Master en Relations internationales', level: 'Master' },
      { name: 'Master en Politique publique', level: 'Master' },
    ],
  },
  {
    name: 'University of Edinburgh',
    city: 'Édimbourg',
    country: 'United Kingdom',
    website: 'https://www.ed.ac.uk',
    applicationUrl: 'https://www.ed.ac.uk/studying/undergraduate/applying',
    specialty: 'Intelligence artificielle, médecine vétérinaire et lettres',
    requiredLanguage: 'Anglais',
    requiredLanguageLevel: 'B2',
    programs: [
      { name: 'Informatique', level: 'Bachelor' },
      { name: 'Médecine vétérinaire', level: 'Bachelor' },
      { name: 'Littérature', level: 'Bachelor' },
      { name: 'Droit', level: 'Bachelor' },
      { name: 'Biologie', level: 'Bachelor' },
      { name: 'Master en Intelligence artificielle', level: 'Master' },
      { name: 'Master en Linguistique', level: 'Master' },
    ],
  },
];

async function seedStudyCountryUniversities() {
  try {
    console.log('🌱 Universités des pays d’études — démarrage…');
    let created = 0;
    let programsCount = 0;

    for (const universityData of universitiesData) {
      const { programs, ...university } = universityData;

      // Upsert par nom (contrainte @unique) : le script est rejouable sans doublon.
      const createdUniversity = await prisma.university.upsert({
        where: { name: university.name },
        update: university,
        create: university,
      });
      created++;

      for (const program of programs) {
        await prisma.universityProgram.upsert({
          where: {
            universityId_name_level: {
              universityId: createdUniversity.id,
              name: program.name,
              level: program.level,
            },
          },
          update: program,
          create: { ...program, universityId: createdUniversity.id },
        });
        programsCount++;
      }

      console.log(`  ✓ ${university.country.padEnd(15)} ${university.name} (${programs.length} filières)`);
    }

    console.log(`\n✅ ${created} universités et ${programsCount} filières traitées.`);
  } catch (error) {
    console.error('❌ Échec du seed :', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

seedStudyCountryUniversities();
