import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const studyCountries = [
  { name: "France", nameFr: "France", region: "Europe", capital: "Paris", flag: "🇫🇷", image: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800", description: "Destination phare pour les étudiants africains. Frais réduits, universités de rang mondial, culture riche.", languageInstruction: ["Français", "Anglais"], tuitionRange: "170€ – 3 770€/an (public)", livingCost: "800€ – 1 200€/mois", visaDifficulty: "Modéré", scholarshipAvailable: true, popularScholarships: ["Bourse Eiffel", "Campus France", "AFD"], popularPrograms: ["Ingénierie", "Business", "Médecine", "Droit", "Sciences"], admissionRequirements: ["Baccalauréat", "Lettre de motivation", "Parcoursup/DAP"], topUniversities: ["Sorbonne", "Sciences Po", "École Polytechnique", "HEC Paris"], processingTimeVisa: "3-8 semaines", studyAvailable: true, isValidated: true },
  { name: "Canada", nameFr: "Canada", region: "Amérique du Nord", capital: "Ottawa", flag: "🇨🇦", image: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800", description: "Bilinguisme français-anglais, immigration facilitée après les études, qualité de vie exceptionnelle.", languageInstruction: ["Français", "Anglais"], tuitionRange: "14 000$ – 35 000$/an (internationaux)", livingCost: "1 000$ – 1 800$/mois", visaDifficulty: "Modéré", scholarshipAvailable: true, popularScholarships: ["Bourse Vanier", "IDRC", "Provinces (Québec)"], popularPrograms: ["Informatique", "Business", "Génie", "Santé", "Finance"], admissionRequirements: ["Relevés de notes", "IELTS/TOEFL ou DELF", "LM"], topUniversities: ["Université de Montréal", "McGill", "UBC", "University of Toronto"], processingTimeVisa: "4-12 semaines", studyAvailable: true, isValidated: true },
  { name: "Germany", nameFr: "Allemagne", region: "Europe", capital: "Berlin", flag: "🇩🇪", image: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800", description: "Frais de scolarité quasi nuls dans les universités publiques. Leader mondial en ingénierie et technologie.", languageInstruction: ["Allemand", "Anglais"], tuitionRange: "0€ – 3 000€/semestre (frais de gestion)", livingCost: "700€ – 1 100€/mois", visaDifficulty: "Modéré", scholarshipAvailable: true, popularScholarships: ["DAAD", "Erasmus+", "Heinrich Böll"], popularPrograms: ["Ingénierie", "Informatique", "Sciences", "Architecture", "Médecine"], admissionRequirements: ["Baccalauréat (avec équivalence)", "TestDaF ou IELTS", "Blocked account"], topUniversities: ["TU Munich", "Heidelberg", "LMU Munich", "Berlin FU"], processingTimeVisa: "4-8 semaines", studyAvailable: true, isValidated: true },
  { name: "United Kingdom", nameFr: "Royaume-Uni", region: "Europe", capital: "Londres", flag: "🇬🇧", image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800", description: "Diplômes reconnus mondialement. Programme Bachelor en 3 ans, Master en 1 an.", languageInstruction: ["Anglais"], tuitionRange: "10 000£ – 38 000£/an", livingCost: "1 000£ – 1 800£/mois", visaDifficulty: "Élevé", scholarshipAvailable: true, popularScholarships: ["Chevening", "Commonwealth", "Gates Cambridge"], popularPrograms: ["Finance", "Droit", "Médecine", "Business", "Art & Design"], admissionRequirements: ["IELTS 6.0+", "Personal Statement", "Références académiques"], topUniversities: ["Oxford", "Cambridge", "Imperial College", "UCL", "LSE"], processingTimeVisa: "3-8 semaines", studyAvailable: true, isValidated: true },
  { name: "Morocco", nameFr: "Maroc", region: "Afrique", capital: "Rabat", flag: "🇲🇦", image: "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=800", description: "Hub académique africain. Frais accessibles, enseignement en français, diplômes reconnus en Europe.", languageInstruction: ["Français", "Arabe"], tuitionRange: "1 500€ – 6 000€/an", livingCost: "300€ – 600€/mois", visaDifficulty: "Faible", scholarshipAvailable: true, popularScholarships: ["Bourse du Gouvernement Marocain", "OCI", "Bourse Roi Mohammed VI"], popularPrograms: ["Médecine", "Ingénierie", "Droit", "Commerce", "Architecture"], admissionRequirements: ["Baccalauréat", "Concours ou dossier", "Attestation financière"], topUniversities: ["UM5 Rabat", "UCA Marrakech", "Al Akhawayn", "EMI"], processingTimeVisa: "2-4 semaines", studyAvailable: true, isValidated: true },
  { name: "Senegal", nameFr: "Sénégal", region: "Afrique", capital: "Dakar", flag: "🇸🇳", image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800", description: "Pôle universitaire west-africain. Frais très accessibles, ambiance multiculturelle.", languageInstruction: ["Français"], tuitionRange: "200€ – 3 000€/an", livingCost: "200€ – 500€/mois", visaDifficulty: "Très faible", scholarshipAvailable: true, popularScholarships: ["Bourse gouvernement sénégalais", "Campus France Sénégal"], popularPrograms: ["Médecine", "Droit", "Commerce", "Informatique", "Sciences sociales"], admissionRequirements: ["Baccalauréat", "Dossier académique"], topUniversities: ["UCAD Dakar", "ISM", "ESP Dakar", "UVS"], processingTimeVisa: "1-2 semaines", studyAvailable: true, isValidated: true },
  { name: "Netherlands", nameFr: "Pays-Bas", region: "Europe", capital: "Amsterdam", flag: "🇳🇱", image: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800", description: "Leader mondial pour les programmes en anglais. Très ouvert aux internationaux.", languageInstruction: ["Anglais", "Néerlandais"], tuitionRange: "2 000€ – 20 000€/an", livingCost: "900€ – 1 400€/mois", visaDifficulty: "Modéré", scholarshipAvailable: true, popularScholarships: ["Holland Scholarship", "Orange Tulip", "Erasmus+"], popularPrograms: ["Business", "Ingénierie", "Sciences de la vie", "Design", "IT"], admissionRequirements: ["Baccalauréat", "IELTS 6.5+", "Portfolio (Design)"], topUniversities: ["TU Delft", "Amsterdam UVA", "Leiden", "Wageningen"], processingTimeVisa: "3-6 semaines", studyAvailable: true, isValidated: true },
  { name: "Spain", nameFr: "Espagne", region: "Europe", capital: "Madrid", flag: "🇪🇸", image: "https://images.unsplash.com/photo-1543783207-ec64e4d95325?w=800", description: "Coût de vie bas, culture vivante, forte communauté africaine étudiante.", languageInstruction: ["Espagnol", "Anglais (programmes spéciaux)"], tuitionRange: "900€ – 7 000€/an", livingCost: "600€ – 1 000€/mois", visaDifficulty: "Modéré", scholarshipAvailable: true, popularScholarships: ["MAEC-AECID", "Erasmus+"], popularPrograms: ["Architecture", "Tourisme", "Business", "Langues", "Médecine"], admissionRequirements: ["Baccalauréat", "DELE B2 ou IELTS", "Dossier académique"], topUniversities: ["Complutense Madrid", "Barcelone UB", "Salamanque", "Polytechnique Valencia"], processingTimeVisa: "4-6 semaines", studyAvailable: true, isValidated: true },
  { name: "China", nameFr: "Chine", region: "Asie", capital: "Pékin", flag: "🇨🇳", image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800", description: "Bourses généreuses du gouvernement chinois. Leader mondial en sciences et technologie.", languageInstruction: ["Mandarin", "Anglais"], tuitionRange: "2 000$ – 10 000$/an", livingCost: "400$ – 800$/mois", visaDifficulty: "Faible", scholarshipAvailable: true, popularScholarships: ["CSC Government Scholarship", "Confucius Institute", "Provincial scholarships"], popularPrograms: ["Ingénierie", "Médecine (MBBS)", "IT", "Sciences", "Commerce"], admissionRequirements: ["Baccalauréat", "HSK (optionnel pour programmes anglais)", "Bonne santé"], topUniversities: ["Tsinghua", "Pékin University", "Fudan", "Zhejiang"], processingTimeVisa: "2-4 semaines", studyAvailable: true, isValidated: true },
  { name: "Belgium", nameFr: "Belgique", region: "Europe", capital: "Bruxelles", flag: "🇧🇪", image: "https://images.unsplash.com/photo-1491557345352-5929e343eb89?w=800", description: "Coeur de l'Europe, enseignement en français, frais bas pour les universités publiques.", languageInstruction: ["Français", "Néerlandais", "Anglais"], tuitionRange: "835€ – 4 000€/an", livingCost: "800€ – 1 200€/mois", visaDifficulty: "Modéré", scholarshipAvailable: true, popularScholarships: ["ARES", "WBI", "VLIR-UOS"], popularPrograms: ["Droit", "Sciences politiques", "Médecine", "Ingénierie", "Arts"], admissionRequirements: ["Baccalauréat", "Dossier académique", "Attestation financière"], topUniversities: ["KU Leuven", "ULB Bruxelles", "UCLouvain", "Gand"], processingTimeVisa: "3-6 semaines", studyAvailable: true, isValidated: true },
];

const tourismCountries = [
  { name: "France", nameFr: "France", region: "Europe", capital: "Paris", flag: "🇫🇷", image: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800", description: "La ville lumière, les châteaux de la Loire, la Côte d'Azur et la gastronomie française.", currency: "Euro (€)", language: "Français", bestTime: "Avril – Octobre", avgBudgetPerDay: "80€ – 200€", topAttractions: ["Tour Eiffel", "Louvre", "Versailles", "Mont Saint-Michel", "Côte d'Azur"], visaForAfricans: "Schengen requis", processingTimeVisa: "10-15 jours", directFlightsFrom: ["Dakar", "Abidjan", "Douala", "Casablanca", "Lagos"], tourismAvailable: true, isValidated: true },
  { name: "Morocco", nameFr: "Maroc", region: "Afrique", capital: "Rabat", flag: "🇲🇦", image: "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=800", description: "Médinas colorées, désert du Sahara, Atlas enneigé et cuisine épicée. Une expérience unique aux portes de l'Europe.", currency: "Dirham (MAD)", language: "Arabe, Français", bestTime: "Mars – Mai, Septembre – Novembre", avgBudgetPerDay: "30€ – 80€", topAttractions: ["Marrakech Médina", "Désert de Merzouga", "Chefchaouen", "Fès", "Aït Benhaddou"], visaForAfricans: "Sans visa pour la plupart des pays africains", processingTimeVisa: "Visa on arrival ou exemption", directFlightsFrom: ["Dakar", "Abidjan", "Casablanca", "Lagos", "Bamako"], tourismAvailable: true, isValidated: true },
  { name: "United Arab Emirates", nameFr: "Émirats Arabes Unis", region: "Asie", capital: "Abu Dhabi", flag: "🇦🇪", image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800", description: "Dubai, la ville du futur. Architecture époustouflante, shopping, désert et plages de rêve.", currency: "Dirham AED", language: "Arabe, Anglais", bestTime: "Novembre – Avril", avgBudgetPerDay: "80€ – 250€", topAttractions: ["Burj Khalifa", "Dubai Mall", "Palm Jumeirah", "Desert Safari", "Abu Dhabi Mosque"], visaForAfricans: "Visa requis (facile à obtenir en ligne)", processingTimeVisa: "3-5 jours", directFlightsFrom: ["Dakar", "Abidjan", "Lagos", "Nairobi", "Accra"], tourismAvailable: true, isValidated: true },
  { name: "Turkey", nameFr: "Turquie", region: "Europe/Asie", capital: "Ankara", flag: "🇹🇷", image: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800", description: "Pont entre deux continents. Istanbul, Cappadoce, plages turquoise et cuisine légendaire.", currency: "Lire turque (TRY)", language: "Turc, Anglais", bestTime: "Avril – Juin, Septembre – Novembre", avgBudgetPerDay: "30€ – 90€", topAttractions: ["Sainte-Sophie", "Cappadoce", "Ephèse", "Antalya", "Palais Topkapi"], visaForAfricans: "e-Visa en ligne (simple et rapide)", processingTimeVisa: "1-3 jours", directFlightsFrom: ["Dakar", "Abidjan", "Lagos", "Accra", "Nairobi"], tourismAvailable: true, isValidated: true },
  { name: "South Africa", nameFr: "Afrique du Sud", region: "Afrique", capital: "Pretoria", flag: "🇿🇦", image: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800", description: "Le Cap, le Kruger, les vignobles de Stellenbosch et la route des jardins. Une destination incomparable.", currency: "Rand (ZAR)", language: "Anglais, Zoulou, Xhosa", bestTime: "Toute l'année (selon région)", avgBudgetPerDay: "40€ – 120€", topAttractions: ["Cap de Bonne Espérance", "Kruger Park", "Table Mountain", "Robben Island", "Garden Route"], visaForAfricans: "Visa requis pour certains pays africains", processingTimeVisa: "5-10 jours", directFlightsFrom: ["Lagos", "Nairobi", "Dakar", "Addis-Abeba"], tourismAvailable: true, isValidated: true },
  { name: "Thailand", nameFr: "Thaïlande", region: "Asie", capital: "Bangkok", flag: "🇹🇭", image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800", description: "Temples dorés, îles paradisiaques, street food incroyable et hospitalité légendaire.", currency: "Baht (THB)", language: "Thaï, Anglais", bestTime: "Novembre – Avril", avgBudgetPerDay: "30€ – 80€", topAttractions: ["Bangkok Temples", "Chiang Mai", "Phuket", "Koh Samui", "Pai"], visaForAfricans: "Visa on arrival ou exemption (selon pays)", processingTimeVisa: "A l'arrivée", directFlightsFrom: ["Dubai (connexion)", "Nairobi", "Addis-Abeba"], tourismAvailable: true, isValidated: true },
  { name: "Kenya", nameFr: "Kenya", region: "Afrique", capital: "Nairobi", flag: "🇰🇪", image: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800", description: "Grande Migration du Masai Mara, Mount Kenya, côte de Mombasa et culture Maasai.", currency: "Shilling kényan (KES)", language: "Anglais, Swahili", bestTime: "Juillet – Octobre (Grande Migration)", avgBudgetPerDay: "50€ – 200€", topAttractions: ["Masai Mara", "Amboseli", "Diani Beach", "Nairobi Park", "Mount Kenya"], visaForAfricans: "eTA en ligne (simple)", processingTimeVisa: "3-5 jours", directFlightsFrom: ["Addis-Abeba", "Lagos", "Dakar", "Accra"], tourismAvailable: true, isValidated: true },
  { name: "Portugal", nameFr: "Portugal", region: "Europe", capital: "Lisbonne", flag: "🇵🇹", image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800", description: "La destination européenne la plus accessible. Fado, pastéis de nata, Algarve et histoire maritime.", currency: "Euro (€)", language: "Portugais, Anglais", bestTime: "Avril – Octobre", avgBudgetPerDay: "50€ – 120€", topAttractions: ["Lisbonne Alfama", "Porto", "Algarve", "Sintra", "Douro Valley"], visaForAfricans: "Schengen requis", processingTimeVisa: "10-15 jours", directFlightsFrom: ["Dakar", "Accra", "Lagos", "Casablanca"], tourismAvailable: true, isValidated: true },
  { name: "Botswana", nameFr: "Botswana", region: "Afrique", capital: "Gaborone", flag: "🇧🇼", image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800", description: "Delta de l'Okavango, éléphants du Chobe, safari de luxe dans l'une des plus belles réserves d'Afrique.", currency: "Pula (BWP)", language: "Anglais, Setswana", bestTime: "Juin – Octobre", avgBudgetPerDay: "150€ – 500€", topAttractions: ["Okavango Delta", "Chobe Park", "Moremi", "Kalahari", "Makgadikgadi"], visaForAfricans: "Exempt pour la plupart des pays SADC", processingTimeVisa: "Exemption ou visa à l'arrivée", directFlightsFrom: ["Johannesburg", "Nairobi"], tourismAvailable: true, isValidated: true },
  { name: "Rwanda", nameFr: "Rwanda", region: "Afrique", capital: "Kigali", flag: "🇷🇼", image: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800", description: "L'Afrique des mille collines. Gorilles de montagne, Kigali ultra-moderne, lacs et résilience inspirante.", currency: "Franc rwandais (RWF)", language: "Kinyarwanda, Français, Anglais", bestTime: "Juin – Septembre", avgBudgetPerDay: "60€ – 200€", topAttractions: ["Gorilles Volcanoes NP", "Kigali Genocide Memorial", "Lac Kivu", "Nyungwe Forest", "Akagera Park"], visaForAfricans: "Visa on arrival pour tous les Africains", processingTimeVisa: "A l'arrivée", directFlightsFrom: ["Nairobi", "Lagos", "Addis-Abeba", "Johannesburg"], tourismAvailable: true, isValidated: true },
];

const blogs = [
  { title: "Comment obtenir une bourse pour étudier en France en 2026", slug: "bourse-etudier-france-2026", category: "Études", author: "Équipe Midzoe", imageUrl: "https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?w=800", excerpt: "Tout ce que vous devez savoir sur les bourses Eiffel, Campus France et AFD pour financer vos études en France.", body: "Étudier en France est le rêve de millions d'étudiants africains. Chaque année, plusieurs programmes de bourses permettent de financer entièrement ou partiellement ce projet...\n\n## La Bourse Eiffel\nLa bourse d'excellence Eiffel est attribuée par Campus France aux étudiants internationaux en Master ou Doctorat...\n\n## Campus France\nLe programme Campus France accompagne les étudiants dans leur démarche de candidature auprès des universités françaises...\n\n## Nos conseils\n1. Commencez vos démarches 12 mois à l'avance\n2. Préparez un dossier solide avec lettre de motivation en français\n3. Contactez directement les universités pour les bourses internes", publishedAt: new Date("2026-01-10"), isPublished: true },
  { title: "Top 5 des destinations touristiques africaines sous-estimées", slug: "top-5-destinations-africaines-sous-estimees", category: "Tourisme", author: "Équipe Midzoe", imageUrl: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800", excerpt: "Le Rwanda, le Botswana, la Namibie, le Lesotho et São Tomé méritent d'être sur votre liste de voyages.", body: "L'Afrique regorge de destinations magnifiques qui restent méconnues du grand public. Voici 5 destinations que Midzoe recommande absolument...\n\n## 1. Le Rwanda — L'Afrique des Mille Collines\nKigali est aujourd'hui l'une des villes les plus propres et sécurisées d'Afrique...\n\n## 2. Le Botswana — Safari de Luxe\nLe delta de l'Okavango est classé au patrimoine mondial de l'UNESCO...\n\n## 3. La Namibie — Désert et Côtes Sauvages\nLe désert du Namib, l'un des plus vieux du monde, offre des paysages lunaires à couper le souffle...", publishedAt: new Date("2026-01-20"), isPublished: true },
  { title: "Étudier en Allemagne gratuitement : le guide complet", slug: "etudier-allemagne-gratuitement-guide", category: "Études", author: "Équipe Midzoe", imageUrl: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800", excerpt: "Les universités publiques allemandes sont quasi gratuites pour tous. Voici comment en profiter.", body: "L'Allemagne est l'une des rares destinations où l'enseignement supérieur est accessible à des frais minimes, même pour les étudiants internationaux...\n\n## Combien ça coûte vraiment ?\nLes frais de scolarité dans les universités publiques sont de 0€ dans la plupart des Länder. Seuls des frais de gestion entre 150€ et 400€ par semestre sont demandés...\n\n## Les conditions d'admission\nPour être admis, vous devez :\n- Avoir votre baccalauréat avec de bons résultats\n- Avoir un niveau B2 en allemand (TestDaF 4) OU étudier en anglais\n- Ouvrir un blocked account de 11 208€\n\n## La bourse DAAD\nLe DAAD (Office Allemand d'Échanges Académiques) propose des bourses couvrant les frais de vie...", publishedAt: new Date("2026-02-05"), isPublished: true },
  { title: "Visa Schengen depuis l'Afrique : nos astuces pour maximiser vos chances", slug: "visa-schengen-afrique-astuces", category: "Visa", author: "Équipe Midzoe", imageUrl: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800", excerpt: "Le visa Schengen est obtenu à plus de 80% quand le dossier est bien préparé. Voici comment faire.", body: "Le visa Schengen permet de visiter 27 pays européens avec un seul visa. Beaucoup pensent que c'est impossible à obtenir depuis l'Afrique, mais avec le bon dossier, le taux de succès dépasse 80%...\n\n## Les documents indispensables\n1. Passeport valide 6 mois après le retour\n2. Réservation d'hôtel (pas définitive)\n3. Billet d'avion aller-retour\n4. Assurance voyage (min. 30 000€)\n5. Relevés bancaires des 3 derniers mois\n6. Lettre de motivation claire et cohérente\n\n## Les erreurs à éviter\n- Ne jamais mentir sur vos revenus\n- Toujours avoir un lien avec votre pays d'origine (emploi, famille, propriété)\n- Éviter les trous inexpliqués dans votre historique bancaire", publishedAt: new Date("2026-02-15"), isPublished: true },
  { title: "Dubai en 7 jours : l'itinéraire parfait pour les Africains", slug: "dubai-7-jours-itineraire", category: "Tourisme", author: "Équipe Midzoe", imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800", excerpt: "Comment profiter de Dubai en une semaine avec un budget maîtrisé : de l'arrivée aux souks, en passant par le désert.", body: "Dubai est la destination numéro 1 des voyageurs africains vers le Moyen-Orient. Voici notre itinéraire recommandé...\n\n## Jour 1-2 : Arrivée et Old Dubai\nCommencez par Al Fahidi, le plus vieux quartier de Dubai, les souks de l'or et des épices...\n\n## Jour 3-4 : Le Dubai Moderne\nBurj Khalifa, Dubai Mall, Dubai Fountain. Réservez la montée au Burj à l'avance pour économiser...\n\n## Jour 5 : Safari dans le désert\nExpérience incontournable ! Sable roux, coucher de soleil, dîner bédouin et nuit sous les étoiles...\n\n## Budget estimé\n- Vol depuis Dakar/Abidjan/Lagos : 300€ – 600€ aller-retour\n- Hôtel 3★ : 60€ – 100€/nuit\n- Repas : 15€ – 40€/jour", publishedAt: new Date("2026-03-01"), isPublished: true },
  { title: "Témoignage : mon expérience d'étudiant africain au Canada", slug: "temoignage-etudiant-africain-canada", category: "Témoignage", author: "Kofi Mensah (Ghana)", imageUrl: "https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800", excerpt: "J'ai quitté Accra pour Montréal en 2023. Voici ce que personne ne vous dit sur la vie étudiante au Canada.", body: "Quand j'ai reçu ma lettre d'admission de l'Université de Montréal, j'avais l'impression que la vie allait changer du tout au tout. Et effectivement, elle a changé — mais pas toujours comme prévu...\n\n## Les bonnes surprises\nLe bilinguisme est un atout énorme. Mon français m'a ouvert des portes que mes collègues anglophones n'avaient pas. J'ai trouvé un stage à peine 3 mois après mon arrivée...\n\n## Les défis cachés\nL'hiver montréalais est brutal. -30°C en janvier, ça ne s'invente pas. Prévoyez des vêtements thermiques avant d'arriver...\n\n## Mes conseils pour les futurs étudiants\n1. Arrivez 2 semaines avant le début des cours pour vous installer\n2. Rejoignez les associations africaines dès le premier jour\n3. Travaillez à temps partiel (max 20h/semaine autorisées)", publishedAt: new Date("2026-03-10"), isPublished: true },
  { title: "Comment économiser sur son billet d'avion depuis l'Afrique", slug: "economiser-billet-avion-afrique", category: "Conseils", author: "Équipe Midzoe", imageUrl: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800", excerpt: "Réserver 3 mois à l'avance, voyager en semaine et utiliser les bons outils peut diviser votre budget vol par deux.", body: "Le billet d'avion représente souvent la plus grande dépense d'un voyage. Voici les stratégies testées par l'équipe Midzoe...\n\n## Quand réserver ?\nLe sweet spot est entre 6 et 10 semaines avant le départ pour les vols internationaux depuis l'Afrique...\n\n## Les meilleurs outils\n- Google Flights (alertes de prix)\n- Skyscanner (comparaison)\n- Kayak (flexibilité de dates)\n\n## Les hubs africains les moins chers\n- Casablanca (Royal Air Maroc) → Europe\n- Addis-Abeba (Ethiopian Airlines) → monde entier\n- Nairobi (Kenya Airways) → Asie et Amériques\n- Abidjan (Air Côte d'Ivoire) → Europe", publishedAt: new Date("2026-03-20"), isPublished: true },
  { title: "Les 10 erreurs à éviter quand on postule dans une université étrangère", slug: "erreurs-candidature-universite-etrangere", category: "Études", author: "Équipe Midzoe", imageUrl: "https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?w=800", excerpt: "Un dossier de candidature mal préparé peut ruiner des années de travail. Voici les pièges à éviter absolument.", body: "Chaque année, des milliers de candidatures excellentes sont rejetées à cause d'erreurs évitables. Après avoir accompagné plus de 500 étudiants, voici ce que nous avons observé...\n\n## Erreur 1 : Envoyer la même lettre de motivation partout\nChaque université veut se sentir unique. Votre lettre doit mentionner spécifiquement pourquoi CETTE université...\n\n## Erreur 2 : Attendre la dernière minute\nLes meilleures places se remplissent dès octobre pour une rentrée en septembre suivant...\n\n## Erreur 3 : Négliger la traduction officielle\nVos documents doivent être traduits par un traducteur assermenté, pas par Google Translate...\n\n## Erreur 4 : Oublier le plan B\nCandidatez dans au moins 5 établissements. Le rejet fait partie du processus.", publishedAt: new Date("2026-04-01"), isPublished: true },
];

async function main() {
  console.log('Seeding study countries...');
  for (const c of studyCountries) {
    await prisma.studyCountry.upsert({
      where: { name: c.name },
      update: c,
      create: c,
    });
  }
  console.log(`✅ ${studyCountries.length} study countries seeded`);

  console.log('Seeding tourism countries...');
  for (const c of tourismCountries) {
    await prisma.tourismCountry.upsert({
      where: { name: c.name },
      update: c,
      create: c,
    });
  }
  console.log(`✅ ${tourismCountries.length} tourism countries seeded`);

  console.log('Seeding blogs...');
  for (const b of blogs) {
    await prisma.blog.upsert({
      where: { slug: b.slug },
      update: b,
      create: b,
    });
  }
  console.log(`✅ ${blogs.length} blog posts seeded`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
